### ISSUE TITLE
make OpenAPI path parameters reusable

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-maps#71]
Assuming https://github.com/opengeospatial/ogcapi-maps/blob/master/openapi/swaggerhub/maps.yaml as the current OpenAPI definition for OAMaps, it would be valuable for the parameters as identified in the various `/paths` objects to be reusable by downstream applications (meaning to move these parameters into `#/components` accordingly.

**Comment by FirePing32** [comment]
These can be put as seperate components as they have been used at multiple places-
```yaml
- name: f
  in: query
```
```yaml
required: false
style: form
explode: false
schema:
  type: string
  enum:
  - application/json
  - text/html
example: application/json
```
```yaml
required: false
style: form
explode: false
```
```yaml
name: f
in: query
description: |-
  The format of the response. If no value is provided, the standard http
  rules apply, i.e., the accept header is used to determine the format.

  Pre-defined values are "json" and "html". The response to other
  values is determined by the server.
```
It will be checked whether snippet 2 can be implemented at a place, followed by snippet 3, as snippet 2 also contains snippet 3 parameters.
Same will be for snippet 1 & 4. Should I make a PR now ?
